# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Greetings
    echo See https://aka.ms/yaml for YAML schema reference
  displayName: 'Run a multi-line script'

- task: Bash@3
  displayName: Veracode Container Security scan
  inputs:
    targetType: inline
    script: |
      pwd
      export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_SECRET)
      curl -fsS https://tools.veracode.com/veracode-cli/install | bash 
      ./veracode version
      pwd
      ls
      ./veracode scan --type directory --source $(System.DefaultWorkingDirectory) --format json --output ./scan.json

- task: PublishPipelineArtifact@1
  displayName: Publish Artifact
  inputs:
    artifactName: veracode-scan-results
    targetPath: $(System.DefaultWorkingDirectory)/scan.json