# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  displayName: Veracode Container Security scan
  inputs:
    targetType: inline
    script: |
      pwd
      export VERACODE_API_KEY_ID=$(VERACODE_API_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_SECRET)
      echo installing...
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh > ./install.log 2>&1
      ./veracode version
      echo scanning...
      ./veracode scan --type repo --source https://github.com/gmdavef/terragoat --format table --output ./scan_results.txt

- task: PublishBuildArtifacts@1
  displayName: 'Publish da Artifact'
  inputs:
    artifactName: 'veracode-scan-results'
    pathToPublish: '$(System.DefaultWorkingDirectory)/scan_results.txt'